# Generated by Django 2.1.1 on 2018-12-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='types',
            new_name='r_type',
        ),
        migrations.AddField(
            model_name='rule',
            name='field',
            field=models.CharField(default='xyz', max_length=100),
            preserve_default=False,
        ),
    ]
