# Generated by Django 2.1.1 on 2018-12-15 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20181215_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='r_type',
            new_name='Rule_type',
        ),
        migrations.RenameField(
            model_name='rule',
            old_name='field',
            new_name='rule_field',
        ),
    ]
