# Generated by Django 2.1.1 on 2018-12-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20181215_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rule',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
