# Generated by Django 2.1.4 on 2018-12-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20181216_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='ruleDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='ruleFlag',
            field=models.BooleanField(default=True),
        ),
    ]
