# Generated by Django 2.1.4 on 2019-01-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_auto_20181216_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('thingTypeName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('thingTypeProperties', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
