# Generated by Django 2.1.4 on 2019-01-03 15:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuleData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_sql', models.CharField(max_length=1000)),
                ('rule_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('sensor_name', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('sensor_type', models.CharField(max_length=255)),
                ('sensor_attributes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weather_data',
            fields=[
                ('Id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('time_stamp', models.DateTimeField(default=datetime.datetime(2019, 1, 3, 20, 41, 29, 209281))),
            ],
        ),
        migrations.AddField(
            model_name='ruledata',
            name='sensor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SensorData'),
        ),
    ]
