# Generated by Django 2.1.4 on 2018-12-07 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather_data',
            fields=[
                ('City', models.CharField(max_length=255)),
                ('Temperature', models.IntegerField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_stamp', models.DateTimeField(default=datetime.datetime(2018, 12, 7, 12, 0, 0, 662790))),
            ],
        ),
    ]
