# Generated by Django 2.1.1 on 2018-12-15 15:50

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181212_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather_data',
            name='City',
        ),
        migrations.RemoveField(
            model_name='weather_data',
            name='Temperature',
        ),
        migrations.RemoveField(
            model_name='weather_data',
            name='id',
        ),
        migrations.AddField(
            model_name='weather_data',
            name='Id',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weather_data',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 15, 21, 19, 40, 417244)),
        ),
    ]
