# Generated by Django 2.1.4 on 2019-01-03 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190103_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruledata',
            name='sensor_name',
        ),
        migrations.AlterField(
            model_name='weather_data',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 3, 21, 2, 28, 798823)),
        ),
        migrations.DeleteModel(
            name='RuleData',
        ),
    ]
