# Generated by Django 2.1.4 on 2019-01-07 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190103_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='certificate_arn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='certificate_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='certificate_pem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='private_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='public_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weather_data',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 7, 11, 17, 1, 976949)),
        ),
    ]
