# Generated by Django 2.1.1 on 2019-01-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190103_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronData',
            fields=[
                ('SensorName', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('testTime', models.IntegerField()),
                ('api', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='SensorData',
        ),
        migrations.DeleteModel(
            name='ThingRules',
        ),
        migrations.DeleteModel(
            name='Weather_data',
        ),
    ]
