# Generated by Django 2.1.5 on 2019-01-28 04:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190124_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('sensorName', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('sensorType', models.CharField(max_length=255)),
                ('sensorAttributes', models.TextField(blank=True, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=255, null=True)),
                ('arn', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='crondata',
            name='active',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crondata',
            name='SensorName',
            field=models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='crondata',
            name='api',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crondata',
            name='testTime',
            field=models.IntegerField(default=10),
        ),
    ]
