# Generated by Django 2.1.4 on 2019-01-14 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190107_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather_data',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 14, 22, 26, 51, 997382)),
        ),
    ]
