# Generated by Django 2.1.4 on 2019-01-14 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190114_2226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Weather_data',
        ),
    ]
