# Generated by Django 2.1.4 on 2019-01-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_thingrules_rule_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=255)),
                ('policyName', models.CharField(max_length=255)),
                ('policyArn', models.CharField(max_length=2048)),
                ('policyDocument', models.TextField(blank=True, null=True)),
                ('policyVersionId', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
