# Generated by Django 2.1.1 on 2018-12-15 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20181215_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather_data',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 15, 22, 48, 37, 294401)),
        ),
    ]
