# Generated by Django 2.1.5 on 2019-01-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='interval',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='timestamp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
