# Generated by Django 2.1.5 on 2019-01-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crondata',
            name='ruleName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='crondata',
            name='ruleType',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='crondata',
            name='ruleValue',
            field=models.IntegerField(default=0),
        ),
    ]
